import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import { BarChart2, CheckCircle, AlertCircle } from "lucide-react";

const AGREEMENT = `AUTHORIZED AGENCY PARTNER AGREEMENT

This agreement is between The Agency LLC ("Company") and the individual/entity named below ("Regional Director" or "Partner").


1. APPOINTMENT

Company hereby appoints Partner as an Authorized Regional Director for The Agency in the designated territory. This appointment is non-exclusive unless otherwise agreed in writing.


2. INDEPENDENT BUSINESS RELATIONSHIP

Partner is an independent business owner operating their own separate legal entity. This agreement does not create an employment, joint venture, or partnership relationship between Partner and The Agency LLC.

Partner explicitly acknowledges:
  - Partner operates their own independent business
  - Partner is solely responsible for their business expenses, taxes, and employees
  - The Agency LLC has no liability for Partner's business operations or employees
  - Consultants recruited by Partner work for Partner's business — not The Agency LLC
  - Partner is responsible for all agreements with their own consultants


3. PLATFORM LICENSE

Company grants Partner a limited, non-exclusive license to:
  - Access and use The Agency platform
  - Operate under The Agency brand name
  - Use Agency training materials and scripts
  - Access the Agency CRM and scanning tools

License fee: $299/month
Month 1: No fee (promotional period)
Month 2+: $299/month auto-deducted from payouts


4. REVENUE SHARING

Partner earns override commissions on all sales generated by consultants under their Partner account:

  - Audit sale ($99): $10 per sale
  - Monthly Monitor ($49/mo): $5/mo per client
  - Pro Monitor ($79/mo): $8/mo per client
  - Pro + Review Booster ($99/mo): $12/mo per client
  - Website Build ($1,500+): $150 per sale
  - SEO Monthly ($500/mo): $50/mo per client

ALL client payments are collected by The Agency LLC. Partner overrides are calculated and paid weekly every Monday following the same 7-day buffer policy applied to all commissions.


5. PAYMENT TERMS

  - All client payments processed through The Agency LLC payment systems
  - Partner has no authority to collect payments directly from clients
  - Override commissions paid weekly every Monday
  - Minimum $20 payout threshold
  - Platform license fee deducted from first weekly payout each month
  - 7-day buffer on all override commissions


6. NONCOMPETE AND NON-SOLICITATION

6a. NONCOMPETE
During the term of this agreement and for a period of TWO (2) YEARS following termination for any reason, Partner agrees not to:

  i) Develop, own, operate, or participate in any business that provides online presence auditing, reputation management, local SEO reporting, or substantially similar services to local businesses

  ii) License, white-label, or resell any competing platform that provides services substantially similar to The Agency platform

  iii) Build or cause to be built any software platform substantially similar to The Agency platform for competitive purposes

6b. NON-SOLICITATION OF CLIENTS
During the term and for TWO (2) YEARS following termination, Partner agrees not to:

  i) Solicit any client who was introduced to Partner through The Agency platform
  ii) Provide competing services to any client in The Agency database
  iii) Use client contact information obtained through The Agency for any purpose other than Agency business

6c. NON-SOLICITATION OF CONSULTANTS
During the term and for ONE (1) YEAR following termination, Partner agrees not to:

  i) Solicit any consultant who worked under Partner's Agency account to work for a competing business
  ii) Encourage any Agency consultant to leave the Agency platform

6d. GEOGRAPHIC SCOPE
The noncompete applies within the United States.

6e. ACKNOWLEDGMENT
Partner acknowledges that:
  - The Agency platform represents substantial proprietary investment
  - Client relationships represent significant business value
  - The restrictions herein are reasonable in scope and duration
  - Violation would cause irreparable harm entitling The Agency LLC to injunctive relief
  - Partner has had opportunity to consult legal counsel before signing


7. CONFIDENTIALITY

Partner agrees to maintain strict confidentiality regarding:
  - The Agency technology and systems
  - Client information and contact data
  - Pricing structures and commission rates
  - Business strategies and plans
  - Other proprietary information

This obligation survives termination of this agreement indefinitely.


8. INTELLECTUAL PROPERTY

All platform technology, brand assets, training materials, and client data remain the exclusive property of The Agency LLC. Partner acquires no ownership interest in any Agency property.


9. TERRITORY

Partner is assigned a non-exclusive territory upon approval. Territory may be modified with 30 days written notice. Partner agrees not to actively solicit clients outside assigned territory without written approval.


10. BRAND STANDARDS

Partner agrees to:
  - Represent The Agency brand professionally
  - Use only approved marketing materials
  - Not make false claims about services
  - Maintain professional conduct standards
  - Ensure their consultants follow Agency guidelines

Violations of brand standards may result in immediate termination.


11. TERMINATION

Either party may terminate with 30 days notice. Immediate termination without notice for:
  - Fraud or misrepresentation
  - Brand standards violations
  - Noncompete violations
  - Criminal conduct

Upon termination:
  - Platform access terminates immediately
  - All client relationships revert to Agency
  - Override commissions for active clients continue for 30 days then cease
  - Platform license fees for current month deducted from final payout
  - Noncompete obligations survive termination


12. DISPUTE RESOLUTION

Disputes resolved through binding arbitration in Washington State. The prevailing party entitled to attorney fees and costs.


13. GOVERNING LAW

This agreement governed by laws of Washington State.


14. ENTIRE AGREEMENT

This agreement constitutes the complete understanding between parties. Modifications require written consent of both parties.`;

export default function PartnerAgreement() {
  const navigate = useNavigate();
  const { user, isLoadingAuth } = useAuth();
  const [check1, setCheck1] = useState(false);
  const [check2, setCheck2] = useState(false);
  const [check3, setCheck3] = useState(false);
  const [sigName, setSigName] = useState("");
  const [bizName, setBizName] = useState("");
  const [error, setError] = useState("");
  const [signed, setSigned] = useState(false);

  useEffect(() => { const l = document.createElement("link"); l.rel = "stylesheet"; l.href = "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@600;700;800&family=Inter:wght@400;500;600&display=swap"; document.head.appendChild(l); return () => { document.head.removeChild(l); }; }, []);
  useEffect(() => { if (!isLoadingAuth && !user) navigate("/login"); }, [user, isLoadingAuth]);

  const H = { fontFamily: "'Plus Jakarta Sans', sans-serif" };
  const now = new Date();

  const handleSign = () => {
    setError("");
    if (!check1) { setError("You must agree to the Partner Agreement."); return; }
    if (!check2) { setError("You must acknowledge the 2-year noncompete clause."); return; }
    if (!check3) { setError("You must confirm authority to sign."); return; }
    if (!sigName.trim()) { setError("Please type your full legal name."); return; }
    localStorage.setItem("pageaudit_partner_agreement", JSON.stringify({ agreed: true, noncompete: true, authority: true, signature: sigName.trim(), business: bizName.trim(), signed_at: now.toISOString(), email: user?.email }));
    setSigned(true);
    setTimeout(() => navigate("/partner/dashboard"), 2000);
  };

  const cb = (checked, onChange, label) => (
    <label style={{ display: "flex", alignItems: "flex-start", gap: 12, cursor: "pointer" }}>
      <input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} style={{ marginTop: 3, width: 18, height: 18, accentColor: "#2563eb", flexShrink: 0 }} />
      <span style={{ fontSize: 13, color: "#c8d0dc", lineHeight: 1.6 }}>{label}</span>
    </label>
  );

  return (
    <div style={{ minHeight: "100vh", background: "#0a0f1e", fontFamily: "'Inter', sans-serif" }}>
      <nav style={{ background: "rgba(10,15,30,0.9)", borderBottom: "1px solid rgba(255,255,255,0.05)", padding: "14px 24px" }}>
        <div style={{ maxWidth: 800, margin: "0 auto", display: "flex", alignItems: "center", gap: 10 }}>
          <BarChart2 style={{ width: 18, height: 18, color: "#3b82f6" }} />
          <span style={{ ...H, fontWeight: 700, fontSize: 14, color: "#fff" }}>The Agency LLC</span>
        </div>
      </nav>
      <div style={{ maxWidth: 800, margin: "0 auto", padding: "40px 20px 80px" }}>
        <div style={{ textAlign: "center", marginBottom: 32 }}>
          <h1 style={{ ...H, fontSize: 28, fontWeight: 800, color: "#fff", marginBottom: 8 }}>Authorized Agency Partner Agreement</h1>
          <p style={{ color: "#94a3b8", fontSize: 14 }}>Please read carefully and sign below to activate your partner account</p>
          <p style={{ color: "#64748b", fontSize: 12, marginTop: 4 }}>{now.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
        </div>

        <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, padding: 24, maxHeight: 400, overflowY: "auto", marginBottom: 32, scrollbarWidth: "thin", scrollbarColor: "#374151 transparent" }}>
          <pre style={{ color: "#c8d0dc", fontSize: 13, lineHeight: 1.7, whiteSpace: "pre-wrap", fontFamily: "'Inter', sans-serif", margin: 0 }}>{AGREEMENT}</pre>
        </div>

        {signed ? (
          <div style={{ background: "rgba(16,185,129,0.1)", border: "1px solid rgba(16,185,129,0.3)", borderRadius: 12, padding: 24, textAlign: "center" }}>
            <CheckCircle style={{ width: 40, height: 40, color: "#10b981", margin: "0 auto 12px", display: "block" }} />
            <p style={{ ...H, fontSize: 20, fontWeight: 700, color: "#fff", marginBottom: 4 }}>Agreement Signed</p>
            <p style={{ color: "#94a3b8", fontSize: 13 }}>Redirecting to your partner dashboard...</p>
          </div>
        ) : (
          <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, padding: 24 }}>
            <div style={{ display: "flex", flexDirection: "column", gap: 14, marginBottom: 20 }}>
              {cb(check1, setCheck1, "I have read and fully understand the Authorized Agency Partner Agreement")}
              {cb(check2, setCheck2, "I understand and agree to the 2-year noncompete clause. I acknowledge I cannot build a competing platform or solicit Agency clients after termination.")}
              {cb(check3, setCheck3, "I am signing as the authorized representative of my business entity and have authority to bind my company to this agreement.")}
            </div>
            <div style={{ marginBottom: 12 }}>
              <label style={{ display: "block", fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 6 }}>Full Legal Name (digital signature)</label>
              <input type="text" value={sigName} onChange={e => setSigName(e.target.value)} placeholder={user?.full_name || "Your full legal name"}
                style={{ width: "100%", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, padding: "12px 14px", fontSize: 16, color: "#fff", outline: "none", fontStyle: "italic", boxSizing: "border-box" }} />
            </div>
            <div style={{ marginBottom: 16 }}>
              <label style={{ display: "block", fontSize: 13, fontWeight: 600, color: "#94a3b8", marginBottom: 6 }}>Business / LLC Name</label>
              <input type="text" value={bizName} onChange={e => setBizName(e.target.value)} placeholder="Your company name"
                style={{ width: "100%", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, padding: "12px 14px", fontSize: 14, color: "#fff", outline: "none", boxSizing: "border-box" }} />
            </div>
            <p style={{ color: "#64748b", fontSize: 12, marginBottom: 12 }}>Date: {now.toLocaleString()}</p>
            {error && (
              <div style={{ display: "flex", alignItems: "center", gap: 8, background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.3)", borderRadius: 8, padding: "10px 14px", marginBottom: 12 }}>
                <AlertCircle style={{ width: 16, height: 16, color: "#ef4444", flexShrink: 0 }} />
                <p style={{ fontSize: 13, color: "#ef4444" }}>{error}</p>
              </div>
            )}
            <button onClick={handleSign} style={{ width: "100%", background: "#f97316", color: "#fff", fontSize: 16, fontWeight: 700, padding: "16px 0", borderRadius: 10, border: "none", cursor: "pointer", opacity: check1 && check2 && check3 && sigName.trim() ? 1 : 0.5 }}>
              Sign Agreement & Activate My Partner Account
            </button>
            <p style={{ textAlign: "center", color: "#64748b", fontSize: 11, marginTop: 10 }}>Your digital signature, timestamp, and IP address are recorded securely.</p>
          </div>
        )}
      </div>
    </div>
  );
}
